name: 'Automation Github Action'
description: 'Run automation in within the pipeline'
inputs:
  username:
    description: 'Github username'
    required: true
  password:
    description: 'Github Token'
    required: true
  env:
    description: 'Select the Environment to run test against'
    required: true
  product:
    description: 'Select different product'
    required: true
  test-type:
    description: 'Select the type of test to run'
    required: true
outputs:
  passed:
    description: 'Number of tests passed'
  failed:
    description: 'Number of tests failed'
  status:
    description: 'The status of the test run'
runs:
  using: 'docker'
  image: 'Dockerfile.github'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.env }}
    - ${{ inputs.test-type }}
    - ${{ inputs.product }}
