name: 'Run E2E Tests'
description: 'Run e2e test with reporting'
inputs:
  env:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: "dev"
  token:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: "dev"
runs:
  using: "composite"
  steps:
    - name: Docker Login to GitHub Container Registry
      run: 'docker login ghcr.io -u pirasanthan-jesugeevegan -p token'
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--env"
    - "${{ inputs.env }}"
