name: 'Run E2E Tests'
description: 'Run e2e test with reporting'
inputs:
  env:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: "dev"
runs:
  pre: 'docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}'
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--env"
    - "${{ inputs.env }}"
