name: 'Automation Tests'
description: 'Run Automation Tests, Generate Report & Upload to S3'
inputs:
  env:
    description: 'Select the Environment to run test against'
    required: true
    default: 'dev'
    options:
      - 'dev'
      - 'stage'
  test_type:
    description: 'Select the type of test to run'
    required: true
    default: 'ui'
    options:
      - 'ui'
      - 'api'
      - 'pt'
  product:
    description: 'Select different product (demo and test) for testing purposes'
    required: true
    default: 'demo'
    options:
      - 'demo'
      - 'Disaster_Recovery'
      - 'Transaction_Protection'
runs:
  using: 'docker'
  image: 'ghcr.io/coincover/coincover-amt:latest'
  args:
    - bash
    - -c
    - |
      docker run \
      -e GITHUB_TOKEN=${GITHUB_TOKEN} \
      -e USER_NAME=${GITHUB_ACTOR} \
      -v "$(pwd)":/app \
      "ghcr.io/${GITHUB_REPOSITORY}:latest" \
      --env "${{ inputs.env }}" \
      --type "${{ inputs.test_type }}" \
      --product "${{ inputs.product }}" \
      --file demo
