name: 'Run E2E Tests'
description: 'Run e2e test with reporting'
inputs:
  env:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: "dev"
  token:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: "dev"
runs:
  using: 'docker'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Login to GitHub Container Registry
      run: |
        docker login ghcr.io -u pirasanthan-jesugeevegan -p ${{ inputs.token }}
    - name: Run E2E Tests with Docker
      run: |
        docker build -t ghcr.io/pirasanthan-jesugeevegan/github-action-test:${{ inputs.env }} .
        docker run ghcr.io/pirasanthan-jesugeevegan/github-action-test:${{ inputs.env }} --env ${{ inputs.env }}