name: 'Run E2E Tests'
description: 'Run e2e test with reporting'
inputs:
  env:
    description: 'env to run tests'
    required: true
    default: 'dev'
  username:
    description: 'Username used to log against the Docker registry'
    required: true
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
