name: 'Test Playwright Github Action'
description: 'Call an API and get the result'
branding:
  icon: 'award'
  color: 'green'
inputs:
  env:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: "dev"
runs:
  using: 'docker'
  image: 'Dockerfile'
   args: >
    bash -c "
    npm install &&
    ./entrypoint.sh --env ${{ inputs.env }}
    "