FROM alpine:3.10

# Install Docker
RUN apk add --no-cache docker
# Install jq
RUN apk --no-cache add jq

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
 RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]