on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: RUN TESTING
    steps:
      - name: RUN TEST
        uses: pirasanthan-jesugeevegan/github-action-test@master
        with:
          env: "--env dev"
