on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: RUN TESTING
    steps:
      - name: Docker Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: RUN TEST
        uses: pirasanthan-jesugeevegan/github-action-test@master
        with:
          env: 'dev'
          type: 'api'
          product: 'demo'
