on: [push]

jobs:
  run_github_action:
    runs-on: ubuntu-latest
    name: Run job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Automation action step
        uses: ./
        id: results
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          env: 'dev'
          test-type: 'api'
          product: 'demo'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the output time
        run: echo "${{ steps.results.outputs.passed }}"
      - name: Get the output time
        run: echo "${{ steps.results.outputs.failed }}"
      - name: Get the output time
        run: echo "${{ steps.results.outputs.status }}"
